# Generated by Django 4.2.5 on 2023-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0006_kurs_kisa_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
