# Generated by Django 4.2.5 on 2023-09-25 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('kategori', models.ManyToManyField(to='kurs.kategori')),
            ],
        ),
    ]
